name: Deploy Staging

on:
  push:
    branches: [main]
    paths:
      - "environments/staging.manifest.env"

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  deploy:
    environment: staging
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: staging
      env_file_name: .env.staging
      config_file_path: environments/staging.config.env
    secrets: inherit
