name: Deploy Staging

on:
  push:
    branches: [main]
    paths:
      - "environments/staging.manifest.env"

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: staging
    secrets: inherit
